customhost = "database-1.cryzepmmerew.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "hewzhiyou-employee"
customregion = "us-east-1"
